services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootsi
      MYSQL_DATABASE: encryption_db
      MYSQL_USER: si
      MYSQL_PASSWORD: si
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

  fastapi:
    build: 
      context: .
      dockerfile: ./BackendFastApi/Dockerfile
    environment:
      MYSQL_DATABASE: encryption_db
      MYSQL_USER: si
      MYSQL_PASSWORD: si
      MYSQL_HOST: mariadb
      MYSQL_PORT: 3306
    ports:
      - "8000:8000"
    networks:
      - app-network
    restart: always
    volumes: # ADAUGĂ ACEASTĂ SECȚIUNE
      - ./BackendFastApi:/app # Presupun că ai deja asta
      - D:/Facultate/AN_4/SEM_2/SI/Proiect/SI-Proiect/shared_crypto_files:/app/data 

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data: